// Code generated by Slice Machine. DO NOT EDIT.

import AboutBlock from './AboutBlock';
import ContactBlock from './ContactBlock';
import ProjectListingBlock from './ProjectListingBlock';
import ProjectPushBlock from './ProjectPushBlock';
import RandomGridImageBlock from './RandomGridImageBlock';
import SketchBookBlock from './SketchBookBlock';

export {
	AboutBlock,
	ContactBlock,
	ProjectListingBlock,
	ProjectPushBlock,
	RandomGridImageBlock,
	SketchBookBlock,
};

export const components = {
	about_block: AboutBlock,
	contact_block: ContactBlock,
	project_listing_block: ProjectListingBlock,
	project_push: ProjectPushBlock,
	loading_image: RandomGridImageBlock,
	sketch_book: SketchBookBlock,
};
