// Code generated by Slice Machine. DO NOT EDIT.

import LoadingImage from './LoadingImage/index.vue';
import SketchBook from './SketchBook/index.vue';
import Socials from './Socials/index.vue';

export {
	LoadingImage,
	SketchBook,
	Socials,
};

export const components = {
	loading_image: LoadingImage,
	sketch_book: SketchBook,
	socials: Socials,
};
