// Code generated by Slice Machine. DO NOT EDIT.

import Hero from './Hero';
import Image from './Image';
import ImageCards from './ImageCards';
import LoadingImage from './LoadingImage';
import Quote from './Quote';
import SketchBook from './SketchBook';
import Socials from './Socials';
import Text from './Text';
import TextWithImage from './TextWithImage';

export {
	Hero,
	Image,
	ImageCards,
	LoadingImage,
	Quote,
	SketchBook,
	Socials,
	Text,
	TextWithImage,
};

export const components = {
	hero: Hero,
	image: Image,
	image_cards: ImageCards,
	loading_image: LoadingImage,
	quote: Quote,
	sketch_book: SketchBook,
	socials: Socials,
	text: Text,
	text_with_image: TextWithImage,
};
